### ISSUE TITLE
求教分析请求遇到的问题

### ISSUE THREAD

**Issue by wikeys** [Rugel/wustjwxt#1]
倘若还没有开放选课，就是没有具体的选课成功的网络请求，那我要怎么才能成功选到课？

**Comment by Rugel** [comment]
不太明白你的意思？

**Comment by wikeys** [comment]
emmmm，是这个意思，我要写一个选课爬虫，现在学校的教务系统没有确定选课这个按钮。所以等到开放选课的时候，我就在分析，课程也就没有了，，，，

**Comment by Rugel** [comment]
那没办法了，只能等到开放选课的时候分析。

**Comment by wikeys** [comment]
好的谢谢
